// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaqhXQr8eKPUjXipzlttfh86FfiKFc_B0',
    appId: '1:180772469280:web:af0d6dd2748a9b75889a45',
    messagingSenderId: '180772469280',
    projectId: 'wasiporck',
    authDomain: 'wasiporck.firebaseapp.com',
    storageBucket: 'wasiporck.firebasestorage.app',
    measurementId: 'G-QB30BBJBXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2EJYmauLDM1DtlUlvtDL7wHx3kHG7wo0',
    appId: '1:180772469280:android:985f3b7641739236889a45',
    messagingSenderId: '180772469280',
    projectId: 'wasiporck',
    storageBucket: 'wasiporck.firebasestorage.app',
  );
}
